[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
name = "oic"
version = "0.1.0"

[build-dependencies]
bindgen = "0.23.1"
gcc = "0.3.45"

[dependencies]
bitflags = "0.8.2"
error-chain = "0.10.0"
slog = "2.0.2"
